task:
  type: bimanual # single or bimanual
  name: _0118_bi_pick_and_place
  copy_raw_data: True
  single_hand_side: left  # left or right (only used when type is 'single')

recorder:
  output: "./data"
  camera:
    format: "MJPG"
    width: 3840
    height: 800
    auto_exposure: 3  # 1=auto, 3=manual
    exposure: 400  # 手动曝光时间（单位通常为微秒，仅当auto_exposure=3时有效）
    auto_white_balance: 0  # 0=manual, 1=auto
    wb_temperature: 4600  # 手动白平衡色温（单位K，如4000-6500，仅当auto_white_balance=0时有效）
    brightness: 0
    gain: 100
    gamma: 100

  camera_paths:
    left_hand: "/dev/video0"
    right_hand: "/dev/video2"

calculate_width:
  left_hand_aruco_id:
    left_id: 0
    right_id: 1
  right_hand_aruco_id:
    left_id: 2
    right_id: 3
  max_workers: 4
  cam_intrinsic_json_path: "../assets/intri_result/gopro_intrinsics_2_7k.json"
  aruco_dict:
    # predefined: DICT_4X4_50
    predefined: DICT_4X4_50
  marker_size_map:
    0: 0.02
    1: 0.02
    2: 0.02
    3: 0.02

tactile_point_extraction:
  max_workers: 16
  fps_num_points: 256

output_train_data:
  visual_cam_latency: 0.101
  pose_latency: 0.002

  use_inpaint_tag: True
  tag_scale: 1.3
  
  min_episode_length: 10  # min frame number for one episode
  visual_out_res: [224, 224] 
  tactile_out_res: [224, 224]

  use_tactile_img: True
  use_tactile_pc: False 
  use_ee_pose: False

  compression_level: 99
  num_workers: 16
  
  tx_quest_2_ee_left_path: '../assets/tf_cali_result/quest_2_ee_left_hand.npy'
  tx_quest_2_ee_right_path: '../assets/tf_cali_result/quest_2_ee_right_hand.npy'

  use_mask: False
  fisheye_mask_params:
    radius: 390
    center: null
    fill_color: [0, 0, 0] # black 